"""Protocol for :class:`~vs_queue_monitor.engine.QueueMonitorEngine` host integrations."""

from __future__ import annotations

from typing import Any, Callable, Optional, Protocol


class MonitorHooks(Protocol):
    """Scheduling, dialogs, and optional UI side effects."""

    def string_var(self, value: str) -> Any: ...
    def boolean_var(self, value: bool) -> Any: ...

    def schedule(self, ms: int, fn: Callable[[], None]) -> Optional[str]: ...
    def schedule_cancel(self, job: Optional[str]) -> None: ...
    def schedule_idle(self, fn: Callable[[], None]) -> None: ...

    def winfo_exists(self) -> bool: ...

    def show_error(self, title: str, message: str) -> None: ...
    def ask_yes_no(self, title: str, message: str) -> bool: ...

    def append_history(self, message: str) -> None: ...
    def request_redraw_graph(self) -> None: ...

    def show_start_loading(self, show: bool) -> None: ...

    def bell(self) -> None: ...

    def show_threshold_popup(self, position: int, eta_display: str) -> None: ...
    def show_completion_popup(self) -> None: ...

    def destroy_active_popups(self) -> None: ...

    def window_geometry_for_save(self) -> str: ...

    def open_settings_ui(self) -> None:
        """Open settings (e.g. web modal)."""
        ...
